spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: update

server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.security: info
    org.springframework.web: INFO