spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false

server:
  port: 8080

logging:
  level:
    root: WARN
    org.springframework.security: info
    org.springframework.web: INFO